### ISSUE TITLE
ADD the Screenshots in the readme of the working code

### ISSUE THREAD

**Issue by Himanshutiwari15** [Himanshutiwari15/Python-AudioBook-ScreenRecoder#5]
Add the vald working screenshots in the readme

**Comment by hasan-haider** [comment]
Is it available for contribution?

**Comment by hasan-haider** [comment]
#6 
Completed
Wanted to contribute for hacktober. Thanks in advance!

**Comment by Himanshutiwari15** [comment]
yeah, how can you contribute?
and what?
